# Generated by Django 3.2.5 on 2021-08-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
