# Generated by Django 3.2.5 on 2021-08-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_loreobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='loreobject',
            name='world',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='world',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
