# Generated by Django 3.2.5 on 2021-09-03 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_book_on_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loreobject',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.series'),
        ),
    ]
