# Generated by Django 3.2.5 on 2021-08-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210802_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
