# Generated by Django 3.2.5 on 2021-08-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_bookread'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookread',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
