# Generated by Django 3.2.5 on 2021-08-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_bookread_in_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookread',
            name='date_completed',
        ),
        migrations.AddField(
            model_name='bookread',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
