# Generated by Django 3.2.5 on 2021-08-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210805_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRead',
        ),
    ]
