# Generated by Django 3.2.5 on 2021-08-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_delete_bookread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='book',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='user',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
