# Generated by Django 3.2.5 on 2021-08-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_send_sales',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_send_updates',
            field=models.BooleanField(default=True),
        ),
    ]
