# Generated by Django 3.2.5 on 2021-08-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_user_can_send_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_send_wish_sales',
            field=models.BooleanField(default=True),
        ),
    ]
